### ISSUE TITLE
Create relationships between the classes.

### ISSUE THREAD

**Issue by cooperbocko** [DevDogs-UGA/Optimal-Schedule-Builder#166]
Please create the relationships between the classes. https://www.youtube.com/watch?v=5rNk7m_zlAg (9:52:00) Video for reference.

**Comment by MollySohaney** [comment]
I couldn't see any other entity classes other than the class, course, and section. So I created the relationships between the 3 based on the "Course PDF DB" that was in the drive. But I had a question: in the DB that was in the drive, it says that class and section have a one-to-many relationship, but shouldn't it be many-to-many since a section can have multiple class locations?

**Comment by cooperbocko** [comment]
Yes a section can have multiple locations for classes which is what having multiple classes per section is for. But since each class will only ever be a part of a single section, it is one to many. (One section to many classes). Let me know if that clears it up for you.

**Comment by MollySohaney** [comment]
Yes, thank you that makes sense. I didn't it wrong the first time, but I fixed it.
